In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os as os

In [2]:
os.getcwd()
os.chdir("H:\ML")

In [3]:
dataset= pd.read_csv("santader_train.csv")

In [4]:
dataset.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3   ...    \
0                      0.0                      0.0   ...     
1                      0.0                      0.0   ...     
2                      0.0                      0.0   ...     
3                      0.0                      0.0   ...     
4                      0.0                      0.0   ...     

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET  
0                     0.0                     0.0   39205.170000       0  
1                     0.0                     0.0   49278.030000       0  
2                     0.0                     0.0   67333.770000       0  
3                     0.0                     0.0   64007.970000       0  
4                     0.0                     0.0  117310.979016       0  

[5 rows x 371 columns]

In [5]:
dataset.isnull().sum()

ID                               0
var3                             0
var15                            0
imp_ent_var16_ult1               0
imp_op_var39_comer_ult1          0
imp_op_var39_comer_ult3          0
imp_op_var40_comer_ult1          0
imp_op_var40_comer_ult3          0
imp_op_var40_efect_ult1          0
imp_op_var40_efect_ult3          0
imp_op_var40_ult1                0
imp_op_var41_comer_ult1          0
imp_op_var41_comer_ult3          0
imp_op_var41_efect_ult1          0
imp_op_var41_efect_ult3          0
imp_op_var41_ult1                0
imp_op_var39_efect_ult1          0
imp_op_var39_efect_ult3          0
imp_op_var39_ult1                0
imp_sal_var16_ult1               0
ind_var1_0                       0
ind_var1                         0
ind_var2_0                       0
ind_var2                         0
ind_var5_0                       0
ind_var5                         0
ind_var6_0                       0
ind_var6                         0
ind_var8_0          

In [6]:
X=dataset.drop(['ID','TARGET'],1)

In [7]:
y=dataset['TARGET']

In [8]:
cols=X.columns

In [9]:
cols

Index(['var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3', 'imp_op_var40_ult1',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=369)

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=scaler.fit_transform(X)
X=pd.DataFrame(X)
X.columns=cols

In [11]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=0)

In [12]:
y_train.head()

39926    0
28569    0
36753    1
46226    0
67626    0
Name: TARGET, dtype: int64

In [13]:
X_train.head()

var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
39926  0.999764   0.18                 0.0                      0.0   
28569  0.999764   0.20                 0.0                      0.0   
36753  0.999764   0.35                 0.0                      0.0   
46226  0.999764   0.31                 0.0                      0.0   
67626  0.999764   0.40                 0.0                      0.0   

       imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  \
39926                      0.0                      0.0   
28569                      0.0                      0.0   
36753                      0.0                      0.0   
46226                      0.0                      0.0   
67626                      0.0                      0.0   

       imp_op_var40_comer_ult3  imp_op_var40_efect_ult1  \
39926                      0.0                      0.0   
28569                      0.0                      0.0   
36753                      0.0                      0.0   
46226                      0.0                      0.0   
67626                      0.0                      0.0   

       imp_op_var40_efect_ult3  imp_op_var40_ult1    ...     \
39926                      0.0                0.0    ...      
28569                      0.0                0.0    ...      
36753                      0.0                0.0    ...      
46226                      0.0                0.0    ...      
67626                      0.0                0.0    ...      

       saldo_medio_var29_ult3  saldo_medio_var33_hace2  \
39926                     0.0                      0.0   
28569                     0.0                      0.0   
36753                     0.0                      0.0   
46226                     0.0                      0.0   
67626                     0.0                      0.0   

       saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
39926                      0.0                     0.0   
28569                      0.0                     0.0   
36753                      0.0                     0.0   
46226                      0.0                     0.0   
67626                      0.0                     0.0   

       saldo_medio_var33_ult3  saldo_medio_var44_hace2  \
39926                     0.0                      0.0   
28569                     0.0                      0.0   
36753                     0.0                      0.0   
46226                     0.0                      0.0   
67626                     0.0                      0.0   

       saldo_medio_var44_hace3  saldo_medio_var44_ult1  \
39926                      0.0                     0.0   
28569                      0.0                     0.0   
36753                      0.0                     0.0   
46226                      0.0                     0.0   
67626                      0.0                     0.0   

       saldo_medio_var44_ult3     var38  
39926                     0.0  0.005672  
28569                     0.0  0.010978  
36753                     0.0  0.004608  
46226                     0.0  0.003859  
67626                     0.0  0.002655  

[5 rows x 369 columns]

# LOGISTIC REGRESSION

In [14]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_LINEAR = LogisticRegression(random_state = 0)
classifier_LINEAR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
y_pred= classifier_LINEAR.predict(X_test)

In [16]:
classifier_LINEAR.score(X_test,y_test)

0.9581031307550645

In [17]:
from sklearn.model_selection import cross_val_score
cross_val = cross_val_score(classifier_LINEAR,X_train,y_train,cv=5)
print('Average Cross Validation Score for Linear Regression : ',cross_val.mean())

Average Cross Validation Score for Linear Regression :  0.9607833530992151


# KNN

In [ ]:
# # Fitting K-NN to the Training set
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)

In [ ]:
# y_pred

In [ ]:
# classifier.score(X_test,y_test)

In [ ]:
# from sklearn.model_selection import cross_val_score
# cross_val = cross_val_score(classifier,X_train,y_train,cv=5)
# print('Average Cross Validation Score for Linear Regression : ',cross_val.mean())

# DECISION TREE

In [18]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
y_pred=dtree.predict(X_test)

In [19]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
dtree.score(X_test,y_test)

0.9293606945540647

In [21]:
from sklearn.model_selection import cross_val_score
cross_val = cross_val_score(dtree,X_train,y_train,cv=5)
print('Average Cross Validation Score for Linear Regression : ',cross_val.mean())

Average Cross Validation Score for Linear Regression :  0.9304788621985359


# RANDOM FOREST

In [22]:
#RANDOM FOREST REGRESSOR 
from sklearn.ensemble import RandomForestClassifier
rforest = RandomForestClassifier()
rforest.fit(X_train, y_train)
y_pred = rforest.predict(X_test)

In [23]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
rforest.score(X_test,y_test)

0.9522494080505131

In [25]:
from sklearn.model_selection import cross_val_score
cross_val = cross_val_score(rforest,X_train,y_train,cv=5)
print('Average Cross Validation Score for Linear Regression : ',cross_val.mean())

Average Cross Validation Score for Linear Regression :  0.9550118926260744


# SVM

In [ ]:
# # Fitting SVM to the Training set
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'linear', random_state = 0)
# classifier.fit(X_train, y_train)

In [ ]:
# y_pred=classifier.predict(X_test)
# classifier.score(X_test,y_test)

In [ ]:
# from sklearn.model_selection import cross_val_score
# cross_val = cross_val_score(classifier,X_train,y_train,cv=5)
# print('Average Cross Validation Score for Linear Regression : ',cross_val.mean())

# TESTING 


In [28]:
data=pd.read_csv("santader_test.csv")

In [30]:
data.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   2     2     32                 0.0                      0.0   
1   5     2     35                 0.0                      0.0   
2   6     2     23                 0.0                      0.0   
3   7     2     24                 0.0                      0.0   
4   9     2     23                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3    ...      \
0                      0.0                      0.0    ...       
1                      0.0                      0.0    ...       
2                      0.0                      0.0    ...       
3                      0.0                      0.0    ...       
4                      0.0                      0.0    ...       

   saldo_medio_var29_ult3  saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var33_ult1  saldo_medio_var33_ult3  saldo_medio_var44_hace2  \
0                     0.0                     0.0                      0.0   
1                     0.0                     0.0                      0.0   
2                     0.0                     0.0                      0.0   
3                     0.0                     0.0                      0.0   
4                     0.0                     0.0                      0.0   

   saldo_medio_var44_hace3  saldo_medio_var44_ult1  saldo_medio_var44_ult3  \
0                      0.0                     0.0                     0.0   
1                      0.0                     0.0                     0.0   
2                      0.0                     0.0                     0.0   
3                      0.0                     0.0                     0.0   
4                      0.0                     0.0                     0.0   

       var38  
0   40532.10  
1   45486.72  
2   46993.95  
3  187898.61  
4   73649.73  

[5 rows x 370 columns]

In [33]:
NEW= data.drop(['ID'],1)

since logistic gave the best accuracy hence using it for prediction 

In [44]:
y_pred= classifier_LINEAR.predict(NEW)

In [45]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)